-- combined_modules.lua
-- Auto-generated by combine_modules.lua
-- Source files merged: 140

local modules = {}

local dances = {
    {
        name       = "23 hour cinderella",
        desc       = "censored 24 because of someone",
        moduleType = "DANCE",
        assets     = { "24 hour cinderella.anim", "24 hour cinderella.mp3" },
    },
    {
        name       = "aint no loving my man",
        desc       = "shoo wats shoo wats ",
        moduleType = "DANCE",
        assets     = { "aint no loving my man.anim", "aint no loving my man.mp3" },
    },
    {
        name       = "CSGO Bhop",
        desc       = "that one try hard movement in counter strike or left 4 dead",
        moduleType = "DANCE",
        assets     = { "Bhop.anim", "Bhop.mp3" },
    },
    {
        name       = "BloodPop",
        desc       = "only 2021 survivors remember this",
        moduleType = "DANCE",
        assets     = { "BloodPop.anim", "BloodPop.mp3" },
    },
    {
        name       = "Break Dance",
        desc       = "Let's give real vibes to the serverrer",
        moduleType = "DANCE",
        assets     = { "BreakDance.anim", "BreakDance.mp3" },
    },
    {
        name       = "BreakDown",
        desc       = "we will break with this one🔥🔥🔥 (I forgot how it was sorry)",
        moduleType = "DANCE",
        assets     = { "BreakDown.anim", "BreakDown.mp3" },
    },
    {
        name       = "ChronoShift",
        desc       = "couldnt kill the zillean bro",
        moduleType = "DANCE",
        assets     = { "ChronoShift.anim", "ChronoShift.mp3" },
    },
    {
        name       = "Civillian yell",
        desc       = "How does Theo make to not get lost when administrating his dances dawg",
        moduleType = "DANCE",
        assets     = { "CivillianYell.anim", "CivillianYell.mp3" },
    },
    {
        name       = "Cry for me",
        desc       = "I wanna oof myself before hearing this",
        moduleType = "DANCE",
        assets     = { "CryForMe.anim", "CryForMe.mp3" },
    },
    {
        name       = "Ellen doe",
        desc       = "gooning to this btw",
        moduleType = "DANCE",
        assets     = { "Ellen doe.anim", "Ellen doe.mp3" },
    },
    {
        name       = "Everybody gangnam",
        desc       = "sorry Theo but I stealed the mp3 from your dances",
        moduleType = "DANCE",
        assets     = { "EverybodyGangnam.anim", "EverybodyGangnam.mp3" },
    },
    {
        name       = "Gangnam style (dod)",
        desc       = "fresh meat",
        moduleType = "DANCE",
        assets     = { "Gangnam style (dod).anim", "Gangnam style (dod).mp3" },
    },
    {
        name       = "Hakari from fatsaken",
        desc       = "if Steve not adding this, then Ill do it",
        moduleType = "DANCE",
        assets     = { "HakariForsaken.anim", "HakariForsaken.mp3" },
    },
    {
        name       = "Honey Pie",
        desc       = "I remember that I didnt khow what does this song mean in 2023",
        moduleType = "DANCE",
        assets     = { "Honey Pie.anim", "Honey Pie.mp3" },
    },
    {
        name       = "HypnoDance",
        desc       = "tell Theo to go to hell",
        moduleType = "DANCE",
        assets     = { "HypnoDance.anim", "HypnoDance.mp3" },
    },
    {
        name       = "I luv it",
        desc       = "very good yes yes Noober approves",
        moduleType = "DANCE",
        assets     = { "I luv it.anim", "I luv it.mp3" },
    },
    {
        name       = "Insanity",
        desc       = "I have no sanity",
        moduleType = "DANCE",
        assets     = { "Insanity.anim", "Insanity.mp3" },
    },
    {
        name       = "JK unlimited flexworks",
        desc       = "kj but from Shein",
        moduleType = "DANCE",
        assets     = { "JK.anim", "JK.mp3" },
    },
    {
        name       = "Jamal celebration",
        desc       = "lets celebrate",
        moduleType = "DANCE",
        assets     = { "Jamal celebration.anim", "Jamal celebration.mp3" },
    },
    {
        name       = "Jax toy 2",
        desc       = "Nobody buyed me this btw",
        moduleType = "DANCE",
        assets     = { "Jax toy 2.anim", "Jax toy 2.mp3" },
    },
    {
        name       = "Jax toy",
        desc       = "can someone buy me this🥺",
        moduleType = "DANCE",
        assets     = { "Jax toy.anim", "Jax toy.mp3" },
    },
    {
        name       = "Jung justice",
        desc       = "we are justice",
        moduleType = "DANCE",
        assets     = { "Jung justice.anim", "Jung justice.mp3" },
    },
    {
        name       = "Lil buddy was sick",
        desc       = "bro is not tuff mango six seven skibidi warrior🙏🤣",
        moduleType = "DANCE",
        assets     = { "Lil buddy was sick.anim", "Lil buddy was sick.mp3" },
    },
    {
        name       = "Low Cortisol",
        desc       = "no more angry,only good vibes",
        moduleType = "DANCE",
        assets     = { "LowCortisol.anim", "LowCortisol.mp3" },
    },
    {
        name       = "Luffy dance",
        desc       = "almost 9000092773839383 episodes and still doesnt find the one piece",
        moduleType = "DANCE",
        assets     = { "Luffy dance.anim", "Luffy dance.mp3" },
    },
    {
        name       = "MLG",
        desc       = "That feeling when you hit a 360",
        moduleType = "DANCE",
        assets     = { "MLG.anim", "MLG.mp3" },
    },
    {
        name       = "MONTAGEM XONADA",
        desc       = "Boii the phonk is so sigma",
        moduleType = "DANCE",
        assets     = { "MONTAGEM XONADA.anim", "MONTAGEM XONADA.mp3" },
    },
    {
        name       = "macarena",
        desc       = "good dance from like 2022",
        moduleType = "DANCE",
        assets     = { "Macarena.anim", "Macarena.mp3" },
    },
    {
        name       = "Minos Prime",
        desc       = "its Minos prime guys",
        moduleType = "DANCE",
        assets     = { "Minos Prime.anim", "Minos Prime.mp3" },
    },
    {
        name       = "No More Games",
        desc       = "holy peak 🔥",
        moduleType = "DANCE",
        assets     = { "NoMoreGames.anim", "NoMoreGames.mp3" },
    },
    {
        name       = "Pick it up",
        desc       = "holy dead emote lolllllllll",
        moduleType = "DANCE",
        assets     = { "Pick it up.anim", "Pick it up.mp3" },
    },
    {
        name       = "RickRoll",
        desc       = "NOT THIS TROLL AGAAAAAAAIIIIIIIN",
        moduleType = "DANCE",
        assets     = { "rickrolled.anim", "rickrolled.mp3" },
    },
    {
        name       = "I wanna ran away",
        desc       = "this old meme but in uhhhhh reanimate",
        moduleType = "DANCE",
        assets     = { "Runaway.anim", "Runaway.mp3" },
    },
    {
        name       = "6 7",
        desc       = "ts invaded my fyp in 2025 bro",
        moduleType = "DANCE",
        assets     = { "Six Seven.anim", "Six Seven.mp3" },
    },
    {
        name       = "Skeleton shield",
        desc       = "Rahhhhh",
        moduleType = "DANCE",
        assets     = { "Skeleton2.anim", "Skeleton2.mp3" },
    },
    {
        name       = "SlickBack",
        desc       = "someone made a show about this btw",
        moduleType = "DANCE",
        assets     = { "Slickback.anim", "Slickback.mp3" },
    },
    {
        name       = "Soda Pop",
        desc       = "the movie only lasted like 1 week lmao",
        moduleType = "DANCE",
        assets     = { "SodaPop.anim", "SodaPop.mp3" },
    },
    {
        name       = "Sparta Remix",
        desc       = "ts bugged and didnt play the animation, hope it works now",
        moduleType = "DANCE",
        assets     = { "Sparta Remix.anim", "Sparta Remix.mp3" },
    },
    {
        name       = "Tokyo drift",
        desc       = "Im gonna drift, oh yeah",
        moduleType = "DANCE",
        assets     = { "Tokyo drift.anim", "Tokyo drift.mp3" },
    },
    {
        name       = "Wait",
        desc       = "never could say that to someone :sob:",
        moduleType = "DANCE",
        assets     = { "Wait.anim", "Wait.mp3" },
    },
    {
        name       = "with friends",
        desc       = "me and the friends on the lego🔥🔥",
        moduleType = "DANCE",
        assets     = { "WithFriends.anim", "WithFriends.mp3" },
    },
    {
        name       = "XO",
        desc       = "XOXOXOXOOXOXOXOXOXO",
        moduleType = "DANCE",
        assets     = { "XO.anim", "XO.mp3" },
    },
    {
        name       = "Ai niche baby",
        desc       = "youre not tuff lol",
        moduleType = "DANCE",
        assets     = { "ai niche baby.anim", "ai niche baby.mp3" },
    },
    {
        name       = "Aizo",
        desc       = "Idk what to say here",
        moduleType = "DANCE",
        assets     = { "Aizo.anim", "aizo.mp3" },
    },
    {
        name       = "analog horror funk",
        desc       = "so scary waaaaaa :cry:",
        moduleType = "DANCE",
        assets     = { "Analog horror funk.anim", "Analog horror funk.mp3" },
    },
    {
        name       = "angry",
        desc       = "Im very angry",
        moduleType = "DANCE",
        assets     = { "angry.anim", "angry.mp3" },
    },
    {
        name       = "ay mi gatito",
        desc       = "ay mi gatito meow meow",
        moduleType = "DANCE",
        assets     = { "ay mi gatito.anim", "ay mi gatito.mp3" },
    },
    {
        name       = "bang bang bang",
        desc       = "🔫🔫🔫🔫🔫🔫🔫🔫",
        moduleType = "DANCE",
        assets     = { "bang bang bang.anim", "bang bang bang.mp3" },
    },
    {
        name       = "Beat em up",
        desc       = "lets beat these guys boi",
        moduleType = "DANCE",
        assets     = { "beat em up.anim", "beat em up.mp3" },
    },
    {
        name       = "Bones",
        desc       = "bones for my dog heheh",
        moduleType = "DANCE",
        assets     = { "bones.anim", "bones.mp3" },
    },
    {
        name       = "boombox",
        desc       = "oh yeah Im very cool and youre not",
        moduleType = "DANCE",
        assets     = { "boombox.anim", "boombox.mp3" },
    },
    {
        name       = "boomin",
        desc       = "kaboom, yes rico kaboom",
        moduleType = "DANCE",
        assets     = { "booming.anim", "booming.mp3" },
    },
    {
        name       = "Brickbattler",
        desc       = "without lyrics because of hairytwinkle...",
        moduleType = "DANCE",
        assets     = { "Brickbattler.anim", "Brickbattler.mp3" },
    },
    {
        name       = "bumblebee",
        desc       = "Im a bumblebee :3",
        moduleType = "DANCE",
        assets     = { "bumblebee.anim", "bumblebee.mp3" },
    },
    {
        name       = "Butcher vanity",
        desc       = "my wife fr, if someone says its not Ill shoot him",
        moduleType = "DANCE",
        assets     = { "butcher vanity.anim", "butcher vanity.mp3" },
    },
    {
        name       = "cafeteria",
        desc       = "a coffee pls",
        moduleType = "DANCE",
        assets     = { "cafeteria.anim", "cafeteria.mp3" },
    },
    {
        name       = "Cha cha",
        desc       = "rip epik r6 Dancez",
        moduleType = "DANCE",
        assets     = { "cha cha.anim", "cha cha.mp3" },
    },
    {
        name       = "chika edit",
        desc       = "ohhhhh toy chika😛",
        moduleType = "DANCE",
        assets     = { "chika edit.anim", "chika edit.mp3" },
    },
    {
        name       = "Close to you",
        desc       = "close to meeeee.... i think this is not the jsab song",
        moduleType = "DANCE",
        assets     = { "close to you.anim", "close to you.mp3" },
    },
    {
        name       = "Club Penguin",
        desc       = "pls comeback club penguin we miss you",
        moduleType = "DANCE",
        assets     = { "clubPenguin.anim", "clubPenguin.mp3" },
    },
    {
        name       = "coffin",
        desc       = "I ran out of ideas for this one srry",
        moduleType = "DANCE",
        assets     = { "coffin.anim", "coffin.mp3" },
    },
    {
        name       = "company groove",
        desc       = "dont use it for bad, Im watching you",
        moduleType = "DANCE",
        assets     = { "company groove.anim", "company groove.mp3" },
    },
    {
        name       = "Conga",
        desc       = "look guys, a conga dance",
        moduleType = "DANCE",
        assets     = { "conga.anim", "conga.mp3" },
    },
    {
        name       = "criss cross",
        desc       = "peak dance",
        moduleType = "DANCE",
        assets     = { "criss cross.anim", "criss cross.mp3" },
    },
    {
        name       = "cry for me (evilsaken)",
        desc       = "I want you to search a job",
        moduleType = "DANCE",
        assets     = { "cry for me v2.anim", "cry for me v2.mp3" },
    },
    {
        name       = "Cupid",
        desc       = "I wish it was jack stauber cupid",
        moduleType = "DANCE",
        assets     = { "cupid.anim", "cupid.mp3" },
    },
    {
        name       = "Dance with your eyes closed",
        desc       = "I have no eyes AAAAA",
        moduleType = "DANCE",
        assets     = { "dance with your eyes closed.anim", "dance with your eyes closed.mp3" },
    },
    {
        name       = "Doomer",
        desc       = "Doomer✅✅✅✅✅✅✅✅✅",
        moduleType = "DANCE",
        assets     = { "doomer.anim", "doomer.mp3" },
    },
    {
        name       = "Down",
        desc       = "oh yeah time to get down",
        moduleType = "DANCE",
        assets     = { "down.anim", "down.mp3" },
    },
    {
        name       = "DownTown funk",
        desc       = "ohhh ohhh wish a wish a khew khew",
        moduleType = "DANCE",
        assets     = { "downtown.anim", "downtown.mp3" },
    },
    {
        name       = "Electronic swing",
        desc       = "time to get electronic with this",
        moduleType = "DANCE",
        assets     = { "electro swing.anim", "electro swing.mp3" },
    },
    {
        name       = "engineer taunt",
        desc       = "this emote makes me question my life",
        moduleType = "DANCE",
        assets     = { "engineer taunt.anim", "engineer taunt.mp3" },
    },
    {
        name       = "epical",
        desc       = "we are epical and moderators",
        moduleType = "DANCE",
        assets     = { "epical.anim", "epical.mp3" },
    },
    {
        name       = "evil plan",
        desc       = "id rather a master plan",
        moduleType = "DANCE",
        assets     = { "evil plan.anim", "evil plan.mp3" },
    },
    {
        name       = "firework",
        desc       = "bayby im a firewooooooork",
        moduleType = "DANCE",
        assets     = { "firework.anim", "firework.mp3" },
    },
    {
        name       = "floss",
        desc       = "im very cool mama",
        moduleType = "DANCE",
        assets     = { "floss.anim", "floss.mp3" },
    },
    {
        name       = "Gnarly",
        desc       = "thanks bluuman to telling me the name of the dance",
        moduleType = "DANCE",
        assets     = { "gnarly.anim", "gnarly.mp3" },
    },
    {
        name       = "mufasa",
        desc       = "hypno dance eoeo h- wrong dance srry",
        moduleType = "DANCE",
        assets     = { "go mufasa.anim", "go mufasa.mp3" },
    },
    {
        name       = "goat simulator",
        desc       = "me and the bois playing this in 2014",
        moduleType = "DANCE",
        assets     = { "goat simulator.anim", "goat simulator.mp3" },
    },
    {
        name       = "Gojo",
        desc       = "imagine being a KitKat, thats so LLLLL",
        moduleType = "DANCE",
        assets     = { "gojo.anim", "gojo.mp3" },
    },
    {
        name       = "Griddy",
        desc       = "we hitting the Griddy with this",
        moduleType = "DANCE",
        assets     = { "griddy.anim", "griddy.mp3" },
    },
    {
        name       = "I just hit the jackpot",
        desc       = "when you win 10 femboys with maid",
        moduleType = "DANCE",
        assets     = { "Hit the jackpot.anim", "Hit the jackpot.mp3" },
    },
    {
        name       = "ice cream",
        desc       = "one for me pls",
        moduleType = "DANCE",
        assets     = { "ice cream.anim", "ice cream.mp3" },
    },
    {
        name       = "Invincible edit",
        desc       = "Those woobly edits from invincible war",
        moduleType = "DANCE",
        assets     = { "invincible.anim", "invincible.mp3" },
    },
    {
        name       = "Jumpstyle",
        desc       = "What a jump with style huh",
        moduleType = "DANCE",
        assets     = { "jumpstyle.anim", "jumpstyle.mp3" },
    },
    {
        name       = "Kill me baby",
        desc       = "I get a cringe with this dance idk why",
        moduleType = "DANCE",
        assets     = { "kill me baby.anim", "kill me baby.mp3" },
    },
    {
        name       = "kj unlimited flexworks",
        desc       = "jk but not from shein",
        moduleType = "DANCE",
        assets     = { "kj unlimited.anim", "kj unlimited.mp3" },
    },
    {
        name       = "konton boogie",
        desc       = "boogie boogie",
        moduleType = "DANCE",
        assets     = { "konton boogie.anim", "konton boogie.mp3" },
    },
    {
        name       = "lavish",
        desc       = "tatatattatatats turuturuturutrururururu",
        moduleType = "DANCE",
        assets     = { "lavish.anim", "lavish.mp3" },
    },
    {
        name       = "lemon melon cookie",
        desc       = "NO THEO I DID NOT STEAL FROM YOUR MODULES OR OTHERS JSJDKDUJDDKDJJDJDJDK",
        moduleType = "DANCE",
        assets     = { "Lemon Melon Cookie.anim", "Lemon Melon Cookie.mp3" },
    },
    {
        name       = "Locked",
        desc       = "dont you dare to offend us boiii",
        moduleType = "DANCE",
        assets     = { "locked.anim", "locked.mp3" },
    },
    {
        name       = "Lost woods",
        desc       = "If they are lost then find them",
        moduleType = "DANCE",
        assets     = { "lost woods.anim", "lost woods.mp3" },
    },
    {
        name       = "lucky",
        desc       = "I have luck on my side hehe",
        moduleType = "DANCE",
        assets     = { "lucky.anim", "lucky.mp3" },
    },
    {
        name       = "lush life",
        desc       = "we gotta lush at the life",
        moduleType = "DANCE",
        assets     = { "lush life.anim", "lush life.mp3" },
    },
    {
        name       = "Magic maid",
        desc       = "I thinking smth else with the name tbh",
        moduleType = "DANCE",
        assets     = { "magic maid.anim", "magic maid.mp3" },
    },
    {
        name       = "Mambo",
        desc       = "mambo or mangos",
        moduleType = "DANCE",
        assets     = { "mambo.anim", "mambo.mp3" },
    },
    {
        name       = "mannrobics",
        desc       = "Brrr skibidi doo dop yes yes",
        moduleType = "DANCE",
        assets     = { "mannrobics.anim", "mannrobics.mp3" },
    },
    {
        name       = "Metro man 2",
        desc       = "Isho isho isho isho",
        moduleType = "DANCE",
        assets     = { "metro man 2.anim", "metro man 2.mp3" },
    },
    {
        name       = "miku miku beam",
        desc       = "miku is better than teto frfrfrfr",
        moduleType = "DANCE",
        assets     = { "miku miku beam.anim", "miku miku beam.mp3" },
    },
    {
        name       = "miss the quiet",
        desc       = "4 minute dance, daaam",
        moduleType = "DANCE",
        assets     = { "miss the quiet.anim", "miss the quiet.mp3" },
    },
    {
        name       = "monster",
        desc       = "holy shi, Eminem",
        moduleType = "DANCE",
        assets     = { "monster.anim", "monster.mp3" },
    },
    {
        name       = "Moongazer",
        desc       = "Why did gooblox made that hard to extract a dance from epik r6 dancezz and this dance is not even from his dances",
        moduleType = "DANCE",
        assets     = { "Moongazer.anim", "Moongazer.mp3" },
    },
    {
        name       = "muffin time",
        desc       = "what time is it",
        moduleType = "DANCE",
        assets     = { "muffin time.anim", "muffin time.mp3" },
    },
    {
        name       = "Neco arc",
        desc       = "Not that cat",
        moduleType = "DANCE",
        assets     = { "neco arc.anim", "neco arc.mp3" },
    },
    {
        name       = "No hands",
        desc       = "Where are my hands waaaa",
        moduleType = "DANCE",
        assets     = { "no hands.anim", "no hands.mp3" },
    },
    {
        name       = "Oh who is you",
        desc       = "Who is that guy",
        moduleType = "DANCE",
        assets     = { "oh who is you.anim", "oh who is you.mp3" },
    },
    {
        name       = "Orange Justice",
        desc       = "Im shooting you if you say its from skibidi toilet",
        moduleType = "DANCE",
        assets     = { "Orange justice.anim", "Orange justice.mp3" },
    },
    {
        name       = "Otsukare Summer",
        desc       = "can someone be my friend so I have someone to dance with?",
        moduleType = "DANCE",
        assets     = { "otsukare.anim", "otsukare.mp3" },
    },
    {
        name       = "parrot party",
        desc       = "dont mind me chilling in Minecraft",
        moduleType = "DANCE",
        assets     = { "PARROT PARTY.anim", "PARROT PARTY.mp3" },
    },
    {
        name       = "La peligrosa",
        desc       = "Be careful its dangerous",
        moduleType = "DANCE",
        assets     = { "peligrosa.anim", "peligrosa.mp3" },
    },
    {
        name       = "Pick Up The Phone",
        desc       = "is that a forsaken reference?!?! (pls get the joke)",
        moduleType = "DANCE",
        assets     = { "PickThePhone.anim", "PIckThePhone.mp3" },
    },
    {
        name       = "popStar",
        desc       = "youre my rockstar",
        moduleType = "DANCE",
        assets     = { "popStar.anim", "popStar.mp3" },
    },
    {
        name       = "RANGING",
        desc       = "When you lose a clash royale match",
        moduleType = "DANCE",
        assets     = { "Raging.anim", "raging.mp3" },
    },
    {
        name       = "Say it",
        desc       = "Say it cmon",
        moduleType = "DANCE",
        assets     = { "say it.anim", "say it.mp3" },
    },
    {
        name       = "Schadenfreude",
        desc       = "pls don't use it to be toxic yk",
        moduleType = "DANCE",
        assets     = { "schadenfreude.anim", "schadenfreude.mp3" },
    },
    {
        name       = "shake it",
        desc       = "oh yeah time to shake our",
        moduleType = "DANCE",
        assets     = { "shake it.anim", "shake it.mp3" },
    },
    {
        name       = "Shattered hopes",
        desc       = "when someone ships you with a man",
        moduleType = "DANCE",
        assets     = { "shattered hopes.anim", "shattered hopes.mp3" },
    },
    {
        name       = "Shout",
        desc       = "I hope a bridge doesnt fall while Im on a bus",
        moduleType = "DANCE",
        assets     = { "Shout.anim", "Shout.mp3" },
    },
    {
        name       = "shucks",
        desc       = "aw shucks",
        moduleType = "DANCE",
        assets     = { "shucks.anim", "shucks.mp3" },
    },
    {
        name       = "snowy",
        desc       = "snowy of snowTown",
        moduleType = "DANCE",
        assets     = { "snowy.anim", "snowy.mp3" },
    },
    {
        name       = "Speed covering mouth",
        desc       = "neck hurts neck hurts neck hurts",
        moduleType = "DANCE",
        assets     = { "speed covering.anim", "speed covering.mp3" },
    },
    {
        name       = "speed driving",
        desc       = "is not THAT serious bro",
        moduleType = "DANCE",
        assets     = { "speed driving.anim", "speed driving.mp3" },
    },
    {
        name       = "Spooky month",
        desc       = "Its spooky time",
        moduleType = "DANCE",
        assets     = { "spooky month.anim", "spooky month.mp3" },
    },
    {
        name       = "stereo hearts",
        desc       = "peak ball music",
        moduleType = "DANCE",
        assets     = { "stereo hearts.anim", "stereo hearts.mp3" },
    },
    {
        name       = "Sturdy",
        desc       = "WE GETTING STURDY WITH THIS ONE🔥🔥🔥",
        moduleType = "DANCE",
        assets     = { "sturdy.anim", "sturdy.mp3" },
    },
    {
        name       = "subterFuge",
        desc       = "if someone khows wheres is this from pls dm me",
        moduleType = "DANCE",
        assets     = { "SubterFuge.anim", "SubterFuge.mp3" },
    },
    {
        name       = "Survivalist",
        desc       = "hop on Minecraft bro",
        moduleType = "DANCE",
        assets     = { "Survivalist.anim", "Survivalist.mp3" },
    },
    {
        name       = "teto territory",
        desc       = "tetotetotetotetotetotheooooooooooooo",
        moduleType = "DANCE",
        assets     = { "teto territory.anim", "teto territory.mp3" },
    },
    {
        name       = "the hero",
        desc       = "is that you Richard?",
        moduleType = "DANCE",
        assets     = { "the hero.anim", "the hero.mp3" },
    },
    {
        name       = "these cuffs",
        desc       = "AAAAAAAAAAAAA",
        moduleType = "DANCE",
        assets     = { "these cuffs.anim", "these cuffs.mp3" },
    },
    {
        name       = "tick tock",
        desc       = "WTF IS STEVE PYTHON FILE DOING TO THIS DANCE",
        moduleType = "DANCE",
        assets     = { "tick tock.anim", "tick tock.mp3" },
    },
    {
        name       = "topbot",
        desc       = "ohhh yeah im a dancing robot",
        moduleType = "DANCE",
        assets     = { "topbot.anim", "topbot.mp3" },
    },
    {
        name       = "Umamusume",
        desc       = "wtf is that name dang",
        moduleType = "DANCE",
        assets     = { "umamusume.anim", "umamusume.mp3" },
    },
    {
        name       = "Where you going man",
        desc       = "Im really curious",
        moduleType = "DANCE",
        assets     = { "where you going.anim", "where you going.mp3" },
    },
    {
        name       = "wobbly edit",
        desc       = "Average invincible edit",
        moduleType = "DANCE",
        assets     = { "wobbly edit.anim", "wobbly edit.mp3" },
    },
    {
        name       = "work to the beat",
        desc       = "I dont follow mr beats srry",
        moduleType = "DANCE",
        assets     = { "work to the beat.anim", "work to the beat.mp3" },
    },
    {
        name       = "wow caine part 1",
        desc       = "wow Caine, that's funny",
        moduleType = "DANCE",
        assets     = { "wow caine 1.anim", "wow caine.mp3" },
    },
    {
        name       = "wow caine part 2",
        desc       = "could you say it with a little more gusto",
        moduleType = "DANCE",
        assets     = { "wow caine 2.anim", "wow caine.mp3" },
    },
    {
        name       = "you are a pirate",
        desc       = "free Minecraft APK.com",
        moduleType = "DANCE",
        assets     = { "you are a pirate.anim", "you are a pirate.mp3" },
    },
    {
        name       = "Yuji Edit",
        desc       = "Mid edit from tt",
        moduleType = "DANCE",
        assets     = { "Yuji Edit.anim", "Yuji Edit.mp3" },
    },
}

for i = 1, #dances do
    local d = dances[i]
    table.insert(modules, function()
        local m = {}
        local animator = nil
        local start    = 0

        m.ModuleType  = d.moduleType
        m.Name        = d.name
        m.Description = d.desc
        m.Assets      = d.assets

        m.Config = function(parent)
            if Util_CreateText then
                Util_CreateText(parent, "No settings.", 14, Enum.TextXAlignment.Center)
            end
        end

        m.SaveConfig = function() return {} end
        m.LoadConfig = function(save) end

        m.Init = function(figure)
            local anim = d.assets[1]
            local song = d.assets[2]
            if song then
                SetOverrideDanceMusic(AssetGetContentId(song))
            end
            start           = os.clock()
            animator        = AnimLib.Animator.new()
            animator.rig    = figure
            animator.track  = AnimLib.Track.fromfile(AssetGetPathFromFilename(anim))
            animator.looped = true
            animator.speed  = 1
        end

        m.Update = function(dt, figure)
            if animator then
                animator:Step(GetOverrideDanceMusicTime())
            end
        end

        m.Destroy = function(figure)
            animator = nil
        end

        return m
    end)
end

return modules
